We are going to use supabase but querying it through api so no js client needed and changing to other system would be easier.

** Queries

**** Matches
They are sorted by /played_at/ field.

#+BEGIN_SRC bash
curl 'https://orqwiubnozfouaqyywah.supabase.co/rest/v1/CLOSSPAD_match?select=*&order=played_at.asc' \
    -H "apikey: SUPABASE_CLIENT_ANON_KEY" \
    -H "Authorization: Bearer SUPABASE_CLIENT_ANON_KEY"
#+END_SRC


** Tasks [3/7]

*** DONE [#A] BUG next day
when clicked in the last one 1-1-1970 is selected, and no disable working
*** DONE [#A] Review code
/event-handler/ code structure in replicant examples to use some of the ideas there.
*** DONE [#A] BUG deploy.sh
main.js no se están versionando/modificando -> subiendo
*** TODO [#A] Better keywordization
so =played_at= becomes =played-at=. Do not use libraries but code from scratch.
*** TODO [#B] Load session on start
when app is first time loaded/rendered, it must read from localStorage the session from supabase and save into atom dispatching.
*** TODO [#B] Rows animations
using some js library so I can learn js interop too.
*** TODO [#B] Adding configuration
and save into local storage with some /effect/.
*** TODO [#C] Rating system configurable
through some dialog or expandible widget.



** Pages

*** =GET= Matches/classification
/match/2025-04-07
merge
